### ISSUE TITLE
Properly support selenium 3 and geckodriver

### ISSUE THREAD

**Issue by pelme** [pytest-dev/pytest-splinter#99] opened 2017-09-06 12:29 UTC
The latest version of splinter depends on `selenium>=3.4.3`, but requirements-testing.txt in pytest-splinter `selenium<3`.

Running pytest-splinter tests with selenium 3 fails since geckodriver does not exist on Travis CI. We need to install geckodriver before running tests and drop the line from requirements-testing.txt.

**Comment by bubenkoff** [comment] 2017-10-23 15:02
@pelme i tried to update to the latest gecko and ff and run testing suite and it currently fails on the file download tests: it simply freezes after downloading a file, and as i've checked the problem is with the webdriver itself for some reason, it's waiting for page reload (when you do the reload manually then if unfreezes)
do you have ideas how to solve it?
here's the branch i'm testing on: #100

**Comment by soulrebel** [comment] 2017-10-30 16:04
The HTTP command never gets a response, so it's probably a bug in geckodriver.

**Comment by bubenkoff** [comment] 2017-11-05 21:57
@soulrebel but the file download thing is quite important to ignore it, so should we report a bug you think?

**Comment by bubenkoff** [comment] 2018-09-21 10:36
@pelme this is resolved in the latest release

**Closed by bubenkoff** 2018-09-21 10:36 UTC
